### ISSUE TITLE
Version 1.3.1 - Item Dropships go through floor in random spots on all maps.

### ISSUE THREAD

**Issue by PIEisFANTASTIC** [HolographicWings/LethalExpansion#42] opened 2023-12-23 04:44 UTC
On the latest version of LE, I can assume that the tweak to improve item dropships on custom maps broke the placements on official ones. When buying items on any map including the company the item dropship would go through the ground, leaving the items inaccessible.
While I don't have logs, I am pretty confident LE was the culprit as degrading the mod to version 1.2.16 fixed the issue altogether.

**Comment by HolographicWings** [comment] 2023-12-23 11:32
> On the latest version of LE, I can assume that the tweak to improve item dropships on custom maps broke the placements on official ones. When buying items on any map including the company the item dropship would go through the ground, leaving the items inaccessible.
> While I don't have logs, I am pretty confident LE was the culprit as degrading the mod to version 1.2.16 fixed the issue altogether.

Can you show me a screenshot please ?
This happen only in vanilla maps ?

**Comment by taarna23** [comment] 2023-12-23 14:42
I was just coming here to report this! This _only_ occurs _after_ visiting the Christmas Village map. I just finished some time testing to confirm this and that it was not due to a conflict in other mods. I tested this morning with and without other mods.

It appears after visiting the Christmas Village, a secondary dropship is spawned up above the map. Thanks to the Christmas lights it is currently adorned with, you can actually observe it from the ground, weather permitting. After visiting the Christmas Village, the second dropship will be used to deliver items, which always lands in an incorrect position.

One screenshot with other mods, and one without. The dropships are more visible with the HD mod installed, but I put arrows on both images.

![20231223083220_1_edit](https://github.com/HolographicWings/LethalExpansion/assets/46834355/f318bdc2-613d-412a-88cb-d30ecb0ca601)

![20231223082627_1_edit](https://github.com/HolographicWings/LethalExpansion/assets/46834355/d2bfd833-dfaa-45fd-825c-ab8018503a5b)

**Comment by HamedAlmanthari** [comment] 2023-12-23 16:15
i also have this bug. i'm not sure if it's because i have other moon mods or the issue is in the code itself. i have a few screen shots of multiple drop pods in the sky and a few of them land underground or floating in the air.
Orion mod by sfDesat moon:
multiple drop pods, the drop pod landed underground.
![Screenshot 2023-12-23 194710](https://github.com/HolographicWings/LethalExpansion/assets/133137232/3372aafa-b29e-4ba5-93f2-abd9fef6fc6a)
![Screenshot 2023-12-23 194737](https://github.com/HolographicWings/LethalExpansion/assets/133137232/5a14becc-5141-4890-805f-692550958c0a)
![Screenshot 2023-12-23 194754](https://github.com/HolographicWings/LethalExpansion/assets/133137232/c4dda993-495b-4ffb-bc66-89927dde2cda)
Peaches_Castle mod by TeamBridget moon:
multiple drop pods, the drop pod landed in the air.
![Screenshot 2023-12-23 195605](https://github.com/HolographicWings/LethalExpansion/assets/133137232/25042ead-dfd4-4842-ba15-d4054ad23d03)
Ducks_Moons mod by FireNoobsta moon:
![Screenshot 2023-12-23 195926](https://github.com/HolographicWings/LethalExpansion/assets/133137232/c90bd806-c08f-4b61-bb05-549f4916a0ce)
![Screenshot 2023-12-23 195940](https://github.com/HolographicWings/LethalExpansion/assets/133137232/47834e2c-7687-4f4f-a001-da54c3f3ff20)
Aquatis mod by sfDesat moon:
![Screenshot 2023-12-23 200103](https://github.com/HolographicWings/LethalExpansion/assets/133137232/93c5ebc9-71ad-445c-8562-b1215d594d14)
![Screenshot 2023-12-23 200117](https://github.com/HolographicWings/LethalExpansion/assets/133137232/86c40480-6af7-4fe6-825b-e4a6ccae7b52)

**Comment by HolographicWings** [comment] 2023-12-23 17:28
Yes i finally found the issue on my side too
Thanks @taarna23 and @HamedAlmanthari for contributions
The Item Drop Ship wasn't unloaded after leaved modded moons
I fixed it in 1.3.2 and about to release 1.3.3 with more fixes

**Closed** 2024-02-25 00:03 UTC
Labels: bug, fixed
